/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.extendsandroid.minutewatch.publish;

public final class R {
    public static final class array {
        public static final int bill_cycle_date_ends=0x7f050002;
        public static final int catch_calls_between_key=0x7f050004;
        public static final int catch_calls_between_values=0x7f050005;
        public static final int emergency_numbers=0x7f050003;
        public static final int night_time_minutes_hours=0x7f050000;
        public static final int night_time_minutes_values=0x7f050001;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int grey=0x7f060005;
        public static final int solid_blue=0x7f060001;
        public static final int solid_green=0x7f060002;
        public static final int solid_red=0x7f060000;
        public static final int solid_yellow=0x7f060003;
        public static final int white=0x7f060004;
    }
    public static final class dimen {
        public static final int notepad_margin=0x7f070000;
    }
    public static final class drawable {
        public static final int blue=0x7f020009;
        public static final int cancel_button=0x7f020000;
        public static final int cancel_button_background_normal=0x7f020001;
        public static final int cancel_button_background_pressed=0x7f020002;
        public static final int green=0x7f02000a;
        public static final int icon=0x7f020003;
        public static final int minute_watch_large_icon=0x7f020004;
        public static final int okay_button=0x7f020005;
        public static final int okay_button_background_normal=0x7f020006;
        public static final int okay_button_background_pressed=0x7f020007;
        public static final int red=0x7f020008;
        public static final int screen_background_black=0x7f02000c;
        public static final int translucent_background=0x7f02000d;
        public static final int transparent_background=0x7f02000e;
        public static final int yellow=0x7f02000b;
    }
    public static final class id {
        public static final int add_whitelist_number=0x7f0a0019;
        public static final int cancel=0x7f0a0002;
        public static final int catch_calls=0x7f0a000e;
        public static final int catch_calls_label=0x7f0a000d;
        public static final int caught=0x7f0a0000;
        public static final int chatview=0x7f0a0006;
        public static final int contactListView=0x7f0a0005;
        public static final int contactnumber=0x7f0a0004;
        public static final int end_of_billing_month=0x7f0a000a;
        public static final int end_of_billing_month_label=0x7f0a0009;
        public static final int minutes_used=0x7f0a0008;
        public static final int minutes_used_label=0x7f0a0007;
        public static final int name=0x7f0a0003;
        public static final int no_numbers_added=0x7f0a0013;
        public static final int okay=0x7f0a0001;
        public static final int pickFromContacts=0x7f0a001a;
        public static final int plan_type=0x7f0a000c;
        public static final int plan_type_label=0x7f0a000b;
        public static final int remove_whitelisted_number=0x7f0a001b;
        public static final int settings=0x7f0a0017;
        public static final int welcome=0x7f0a000f;
        public static final int welcome_okay=0x7f0a0010;
        public static final int whitelist=0x7f0a0018;
        public static final int whitelistInput=0x7f0a0011;
        public static final int whitelistSubmit=0x7f0a0012;
        public static final int whitelistedName=0x7f0a0015;
        public static final int whitelistedNumber=0x7f0a0016;
        public static final int whitelistedNumbersList=0x7f0a0014;
    }
    public static final class layout {
        public static final int confirm=0x7f030000;
        public static final int contactpickerlayout=0x7f030001;
        public static final int listcontactpicker=0x7f030002;
        public static final int main=0x7f030003;
        public static final int welcome=0x7f030004;
        public static final int whitelist=0x7f030005;
        public static final int whitelistadapterlayout=0x7f030006;
    }
    public static final class menu {
        public static final int minutewatch=0x7f090000;
        public static final int whitelist=0x7f090001;
    }
    public static final class string {
        public static final int add_whitelist_number_label=0x7f080020;
        public static final int add_whitelist_number_shortcut=0x7f080021;
        public static final int app_name=0x7f080000;
        public static final int bill_cycle_end_preference_dialog=0x7f080016;
        public static final int bill_cycle_end_preference_summary=0x7f080015;
        public static final int bill_cycle_end_preference_title=0x7f080014;
        /**  Assets for display in CallConfirm 
         */
        public static final int call_confirm_output_text=0x7f08001b;
        public static final int cancel=0x7f08001d;
        public static final int cancel_input=0x7f080026;
        public static final int catch_calls_between_summary=0x7f080018;
        public static final int catch_calls_between_title=0x7f080017;
        public static final int catch_calls_label=0x7f080008;
        public static final int catch_calls_summary=0x7f08000a;
        /** Assets for display in Settings 
         */
        public static final int catch_calls_title=0x7f080009;
        public static final int end_of_billing_month_label=0x7f080006;
        public static final int has_free_night_time_minutes_summary=0x7f08000c;
        public static final int has_free_night_time_minutes_title=0x7f08000b;
        public static final int has_free_weekend_minutes_summary=0x7f08000e;
        public static final int has_free_weekend_minutes_title=0x7f08000d;
        public static final int minutes_per_month_preference_dialog=0x7f080013;
        public static final int minutes_per_month_preference_summary=0x7f080012;
        public static final int minutes_per_month_preference_title=0x7f080011;
        public static final int minutes_used_label=0x7f080005;
        public static final int night_time_minutes_preference_summary=0x7f080010;
        public static final int night_time_minutes_preference_title=0x7f08000f;
        /**  Assets for whitelist activity
         */
        public static final int no_whitelists=0x7f08001f;
        public static final int nonUniqueNumber=0x7f080027;
        public static final int okay=0x7f08001c;
        public static final int pickFromContactsLable=0x7f080024;
        public static final int pickFromContactsShortcut=0x7f080025;
        public static final int plan_type_label=0x7f080007;
        public static final int remove_whitelisted_number_label=0x7f080022;
        public static final int remove_whitelisted_number_shortcut=0x7f080023;
        public static final int reset_toast_message=0x7f08001e;
        public static final int settings_label=0x7f080001;
        public static final int settings_shortcut=0x7f080002;
        /** Assets for display in Welcome Screen 
         */
        public static final int welcome=0x7f080019;
        public static final int welcome_set=0x7f08001a;
        public static final int whitelist_label=0x7f080003;
        public static final int whitelist_shortcut=0x7f080004;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
    }
}
